# Generated by Django 4.2 on 2023-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.BigIntegerField()),
                ('seller', models.CharField(help_text="Enter Seller's Name", max_length=30)),
                ('buyer', models.CharField(help_text="Enter Buyer's Name", max_length=30)),
                ('listingAgent', models.CharField(help_text='Enter Listing Agent', max_length=30)),
                ('buyingAgent', models.CharField(help_text='Enter Buying Agent', max_length=30)),
                ('price', models.PositiveBigIntegerField(help_text='Enter Price')),
                ('propertyAddress', models.CharField(help_text='Enter Property Addresss', max_length=30)),
                ('contractPDF', models.FileField(help_text='Attach Contract', upload_to='')),
                ('contractDate', models.DateField(auto_now_add=True, help_text='Enter Date of Contract')),
                ('mortgage_or_cash', models.CharField(help_text='Enter Mortgage or Cash', max_length=30)),
                ('mortgageAmount', models.PositiveBigIntegerField(help_text='Enter Mortgage Amount')),
                ('escrowAmount', models.PositiveBigIntegerField(help_text='Enter Escrow Amount')),
                ('closedYesNo', models.CharField(help_text="Has the contract closed? Enter 'Yes' or No' ", max_length=30)),
                ('comments', models.TextField(help_text='Enter pertinent information')),
            ],
        ),
        migrations.CreateModel(
            name='ContractActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.BigIntegerField()),
                ('action', models.CharField(max_length=30)),
                ('actionPerson', models.CharField(max_length=30)),
                ('actionCompany', models.CharField(max_length=30)),
                ('actionAction', models.CharField(max_length=30)),
                ('actionFee', models.CharField(max_length=30)),
                ('actionDueDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_num', models.BigIntegerField()),
                ('closeDate', models.DateField(auto_now_add=True, help_text='Enter Close Date')),
                ('propertyAddress', models.CharField(help_text='Enter Property Address', max_length=30)),
                ('closingDocumentsPDF', models.FileField(help_text='Attach closing documents', upload_to='')),
                ('comments', models.TextField(help_text='Enter Pertinent Documents')),
            ],
        ),
    ]
