# Generated by Django 4.2 on 2023-06-13 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(help_text="Enter Seller's Name", max_length=30)),
                ('buyer', models.CharField(help_text="Enter Buyer's Name", max_length=30)),
                ('listingAgent', models.CharField(help_text='Enter Listing Agent', max_length=30)),
                ('buyingAgent', models.CharField(help_text='Enter Buying Agent', max_length=30)),
                ('price', models.PositiveBigIntegerField(help_text='Enter Price')),
                ('contractDate', models.DateTimeField(default=django.utils.timezone.now, help_text='Enter Date of Contract')),
                ('propertyAddress', models.CharField(help_text='Enter Property Addresss', max_length=30)),
                ('AddDate', models.DateField(auto_now_add=True, null=True, verbose_name='created at')),
            ],
            options={
                'ordering': ['seller'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, help_text='First Name', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default=None, help_text='Last Name', max_length=30, null=True)),
                ('title', models.CharField(blank=True, default=None, help_text='Title', max_length=30, null=True)),
                ('company', models.CharField(blank=True, default=None, help_text='Company', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default=None, help_text='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, help_text='Phone', max_length=30, null=True)),
                ('street', models.CharField(blank=True, default=None, help_text='Street', max_length=30, null=True)),
                ('city', models.CharField(blank=True, default=None, help_text='City', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default=None, help_text='State', max_length=30, null=True)),
                ('zip', models.CharField(blank=True, default=None, help_text='Zip Code', max_length=10, null=True)),
                ('role', models.CharField(blank=True, default=None, help_text="What is this person's role?", max_length=10, null=True)),
                ('contracts', models.ManyToManyField(to='realestate_app.contract')),
            ],
            options={
                'verbose_name': 'Person Database',
                'verbose_name_plural': 'people',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractPDF', models.FileField(blank=True, help_text='Attach Contract', null=True, upload_to='contracts/%Y/%m/%d')),
                ('mortgage', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Is there a mortgage?', max_length=30)),
                ('mortgageAmount', models.PositiveBigIntegerField(default=0, help_text='Enter Mortgage Amount')),
                ('escrowAmount', models.PositiveBigIntegerField(help_text='Enter Escrow Amount')),
                ('closedContract', models.BooleanField(default=False)),
                ('comments', models.TextField(help_text='Enter pertinent information')),
                ('updatedAt', models.DateField(auto_now=True, verbose_name='updated at')),
                ('closeDate', models.DateField(help_text='Expected close date:', null=True)),
                ('closingDocumentsPDF', models.FileField(blank=True, help_text='Attach closing documents', null=True, upload_to='closingdocs/%Y/%m/%d')),
                ('closedContractComments', models.TextField(default='No Comment', help_text='Final thoughts?')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.contract')),
            ],
            options={
                'verbose_name': 'Contract Details',
                'ordering': ['comments'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('action', models.CharField(choices=[('Inspection', 'Inspection'), ('Survey', 'Survey'), ('TitleSearch', 'titleSearch'), ('TermiteInspection', 'TermiteInspection'), ('TitleInsurance', 'TitleInsurance'), ('Lawyer', 'Lawyer'), ('MortgageLoan', 'MortgageLoan'), ('MoldInspection', 'MoldInspection'), ('RadonInspection', 'RadonInspection'), ('HandyMan', 'HandyMan'), ('Other_Action_1', 'Other_Action_1'), ('Other_Action_2', 'Other_Action_2'), ('Other_Action_3', 'Other_Action_3')], help_text='What is the specific action to be accomplished?', max_length=30)),
                ('actionPerson', models.CharField(help_text='Person assigned', max_length=30)),
                ('actionCompany', models.CharField(help_text="Person's company", max_length=30)),
                ('actionNextStep', models.CharField(max_length=30)),
                ('actionFee', models.CharField(help_text='Fee', max_length=30)),
                ('actionDueDate', models.DateField(default='', help_text='Date due', null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate_app.contract')),
            ],
            options={
                'verbose_name_plural': 'actions',
            },
        ),
    ]
