# Generated by Django 4.2 on 2023-04-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeDate', models.DateField(auto_now_add=True, help_text='Enter Close Date')),
                ('propertyAddress', models.CharField(help_text='Enter Property Address', max_length=30)),
                ('closingDocumentsPDF', models.FileField(help_text='Attach closing documents', upload_to='')),
                ('comments', models.TextField(help_text='Enter Pertinent Documents')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_num',
        ),
        migrations.RemoveField(
            model_name='contractactions',
            name='contract_num',
        ),
        migrations.AddField(
            model_name='contractactions',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.contract'),
        ),
        migrations.AddField(
            model_name='person',
            name='keyPerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.contract'),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='closing',
            name='finalClosing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.contract'),
        ),
    ]
