# Generated by Django 4.2 on 2023-04-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0002_closing_delete_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('actionPerson', models.CharField(max_length=30)),
                ('actionCompany', models.CharField(max_length=30)),
                ('actionNextStep', models.CharField(max_length=30)),
                ('actionFee', models.CharField(max_length=30)),
                ('actionDueDate', models.DateField(auto_now_add=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.contract')),
            ],
        ),
        migrations.DeleteModel(
            name='ContractActions',
        ),
    ]
