# Generated by Django 4.2 on 2023-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0003_contractaction_delete_contractactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='keyPerson',
        ),
    ]
