# Generated by Django 4.2 on 2023-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0005_alter_closing_closingdocumentspdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='closingDocumentsPDF',
            field=models.FileField(blank=True, help_text='Attach closing documents', null=True, upload_to=''),
        ),
    ]
