# Generated by Django 4.2 on 2023-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0008_closing_createdate_contract_adddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractaction',
            name='actionDueDate',
            field=models.DateField(default='', null=True),
        ),
    ]
