# Generated by Django 4.2 on 2023-04-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0009_alter_contractaction_actionduedate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closing',
            options={'verbose_name': 'Final Closing'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='mortgage_or_cash',
        ),
        migrations.AddField(
            model_name='contract',
            name='mortgage',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Enter Mortgage or Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='AddDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='closedYesNo',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Has the contract closed?', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mortgageAmount',
            field=models.PositiveBigIntegerField(default=0, help_text='Enter Mortgage Amount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updatedAt',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
    ]
