# Generated by Django 4.2 on 2023-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0010_alter_closing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='closedYesNo',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', help_text='Has the contract closed?', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='mortgage',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Is there a mortgage?', max_length=30),
        ),
    ]
