# Generated by Django 4.2 on 2023-05-10 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0011_alter_contract_closedyesno_alter_contract_mortgage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['seller']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name'], 'verbose_name': 'Person Database', 'verbose_name_plural': 'people'},
        ),
        migrations.RenameField(
            model_name='closing',
            old_name='finalClosing',
            new_name='finalContract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='closedYesNo',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractPDF',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='escrowAmount',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='mortgage',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='mortgageAmount',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter Date of Contract'),
        ),
        migrations.CreateModel(
            name='ContractDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractPDF', models.FileField(blank=True, help_text='Attach Contract', null=True, upload_to='')),
                ('mortgage', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Is there a mortgage?', max_length=30)),
                ('mortgageAmount', models.PositiveBigIntegerField(default=0, help_text='Enter Mortgage Amount')),
                ('escrowAmount', models.PositiveBigIntegerField(help_text='Enter Escrow Amount')),
                ('closedYesNo', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', help_text='Has the contract closed?', max_length=30)),
                ('comments', models.TextField(help_text='Enter pertinent information')),
                ('updatedAt', models.DateField(auto_now=True, verbose_name='updated at')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate_app.contract')),
            ],
            options={
                'verbose_name': 'Contract Details',
                'ordering': ['comments'],
            },
        ),
    ]
