# Generated by Django 4.2 on 2023-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0012_alter_contract_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdetail',
            name='closedYesNo',
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='closeDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='closingDocumentsPDF',
            field=models.FileField(blank=True, help_text='Attach closing documents', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Closing',
        ),
    ]
